variables:
  NAMESPACE: sistemas-cultura-mapagoiano
  APP_NAME: mapa-cultural
  ENV: prod
  
include:
  - project: 'openshift-namespaces/templates'
    ref: master
    file: '/php/gitlab-ci-templates.yaml'
