version: '2'
services:
  mapas:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: compose/local/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../src/protected:/var/www/html/protected
      - ../scripts:/var/www/scripts
      - ../compose/config.php:/var/www/html/protected/application/conf/config.php
      - ../compose/local/config.d:/var/www/html/protected/application/conf/config.d
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/private-files
      - ../tests:/var/www/tests
    links:
      - db
      - redis
    environment:

      #GENERAL CONFIGS:
      - APP_LCODE=pt_BR,es_ES
      - APP_MODE=development
      - ACTIVE_THEME=Goias
      - PENDING_PCACHE_RECREATION_INTERVAL=15

      #MAILER CONFIGS:
      - MAILER_USER=705124f9109aa5
      - MAILER_PASS=8858c5656a606b
      - MAILER_SERVER=smtp.mailtrap.io
      - MAILER_FROM=mapacultural@goias.gov.br
      - MAILER_PORT=2525
      - MAILER_PROTOCOL=tls
      
      #AUTH CONFIGS:
      - GOOGLE_RECAPTCHA_SECRET=6LcfzagaAAAAAIuidAGkNQDvOlPVsZWZ6vSCPcfW
      - GOOGLE_RECAPTCHA_SITEKEY=6LcfzagaAAAAACWCkiQZ8hhKp6O5KoKda85eE1d8
#     - AUTH_PROVIDER=Fake

      #ALDIRBLANC CONFIGS:
      - AB_PROJECT_ID=1
      - INC1_OPPORTUNITY_ID=1
      - INC1_OWNER_ID=3
      - INC1_SEAL_ID=1

      - JOBS_INTERVAL=15
      - REDIS_CACHE=redis

      - MAILER_SERVER=mailhog
      - MAILER_PORT=1025
      - MAILER_FROM=sysadmin@localhost
      - MAILER_PROTOCOL= #precisa ficar vazio para o mailhog funcionar
      
      # chaves de teste do google recaptcha
      - GOOGLE_RECAPTCHA_SITEKEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      - GOOGLE_RECAPTCHA_SECRET=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    depends_on:
      - db
      - redis
      - mailhog
      
    stdin_open: true
    tty: true
    
  mailhog: 
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru  

  db:
    restart: unless-stopped
    image: mdillon/postgis:11
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
        #- PGDATA=mapas
    ports:
      - "5470:5432"
    volumes:
      - ../docker-data/postgres:/var/lib/postgresql/data
      - ../../../dump/mapascult_hom.sql:/docker-entrypoint-initdb.d/dump.sql
